sessions:
  max:
    exchange: max
    envVarPrefix: max
  binance:
    exchange: binance
    envVarPrefix: binance
    publicOnly: true

persistence:
  json:
    directory: var/data
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

crossExchangeStrategies:
  - xatrpin:
      tradingExchange: max
      symbol: ETHBTC
      interval: 5m
      window: 14
      multiplier: 10.0
      minPriceRange: 5%
      amount: 100

      referenceExchange: binance
      referencePriceEMA:
        interval: 1m
        window: 14
      orderPriceLossThreshold: -10

backtest:
  startTime: "2018-10-01"
  endTime: "2018-11-01"
  symbols:
    - ETHBTC
  sessions:
    - max
    - binance
  # syncSecKLines: true
  accounts:
    max:
      makerFeeRate: 0.0%
      takerFeeRate: 0.075%
      balances:
        BTC: 1.0
        ETH: 0
